# Generated by Django 4.1.2 on 2023-06-19 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0002_alter_photo_upload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['title']},
        ),
    ]
