# Generated by Django 4.1.2 on 2023-07-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0003_alter_about_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=250)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site_link', models.URLField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='surname',
            field=models.CharField(default='Beka', max_length=250),
        ),
        migrations.AddField(
            model_name='about',
            name='username',
            field=models.CharField(default='Sometging', max_length=250),
        ),
    ]
