# Generated by Django 4.1.2 on 2023-07-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0004_adress_about_surname_about_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Degree', models.CharField(max_length=250)),
                ('univer_name', models.CharField(max_length=250)),
                ('date_graduation', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=250)),
                ('skills_level', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterModelOptions(
            name='adress',
            options={'ordering': ['-adress']},
        ),
        migrations.AddField(
            model_name='about',
            name='skill_text',
            field=models.TextField(default=''),
        ),
    ]
