# Generated by Django 4.1.2 on 2023-07-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0007_alter_about_options_alter_adress_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='upload',
            field=models.ImageField(upload_to='photos/', verbose_name='Фото'),
        ),
    ]
