# Generated by Django 4.1.2 on 2023-07-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0010_download'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='download',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='download',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата Публикации'),
        ),
    ]
